ALTER TABLE ACTIVITIES
ADD ACTIVITY_TITLE VARCHAR2(64) DEFAULT 'Default Title' NOT NULL;

ALTER TABLE ACTIVITIES
RENAME COLUMN ACTIVITY_NAME TO ACTIVITY_DESCRIPTION;

ALTER TABLE ACTIVITIES
MODIFY ACTIVITY_DESCRIPTION VARCHAR2(1024);

ALTER TABLE UNIVERSITIES
ADD LATITUDE NUMBER(10, 6)
ADD LONGITUDE NUMBER(10,6)
ADD COURSES VARCHAR2(32)
ADD WEBSITE VARCHAR2(32)
ADD EMAIL VARCHAR2(32)
ADD CONTACT_NUMBER VARCHAR2(32)
ADD LOGO_LINK VARCHAR2(128);

ALTER TABLE COMPANIES
ADD CODE VARCHAR2(16)
ADD EMAIL VARCHAR2(32)
ADD WEBSITE VARCHAR2(64)
ADD LATITUDE NUMBER(10, 6)
ADD LONGITUDE NUMBER(10,6);
ADD CONTACT_NUMBER VARCHAR2(32)
ADD LOGO_LINK VARCHAR2(128);

ALTER TABLE COMPANIES
RENAME COLUMN NATURE_BUSINESS TO SECTOR;