ALTER TABLE USERS
ADD SEMESTER NUMBER(2)
ADD SUBJECT VARCHAR2(32)
ADD POSITION VARCHAR2(32)
ADD IMAGE_LINK VARCHAR2(512)
ADD CONTACT_NUMBER VARCHAR2(32)
ADD IS_APPROVED NUMBER(1)
ADD ADDRESS VARCHAR2(512);