ALTER TABLE ACTIVITIES
ADD ACTIVITY_TITLE VARCHAR2(64) DEFAULT 'Default Title' NOT NULL;

ALTER TABLE ACTIVITIES
RENAME COLUMN ACTIVITY_NAME TO ACTIVITY_DESCRIPTION;

ALTER TABLE ACTIVITIES
MODIFY ACTIVITY_DESCRIPTION VARCHAR2(1024) NOT NULL;