BEGIN
EXECUTE IMMEDIATE 'DROP USER INTERNTRACK CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN -- Ignore error if the user does not exist
            RAISE;
END IF;
END;
/

CREATE USER INTERNTRACK IDENTIFIED BY oracle;
GRANT CONNECT, RESOURCE TO INTERNTRACK;