name: myjavajava

services:
  app:
    container_name: java_app
    image: mcr.microsoft.com/devcontainers/java:1-17-bookworm
    command: sleep infinity
    volumes:
      - ..:/code:cached
    networks:
      - javajavajava

  db:
    container_name: java_db
    image: wnameless/oracle-xe-11g-r2
    ports:
      - "1521:1521"
      - "8080:8080"
    environment:
      ORACLE_ALLOW_REMOTE: "true"
      ORACLE_DISABLE_ASYNCH_IO: "true"
    networks:
      - javajavajava

networks:
  javajavajava:
    name: javajavajava
    driver: bridge
